# Generated by Django 5.0.1 on 2024-01-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ulica", models.CharField(max_length=100)),
                ("nr_domu", models.CharField(max_length=10)),
                ("nr_mieszkania", models.CharField(max_length=10)),
                ("kod_pocztowy", models.CharField(max_length=10)),
                ("miasto", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Uzytkownik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("haslo", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("imie", models.CharField(max_length=100)),
                ("nazwisko", models.CharField(max_length=100)),
                ("numer_telefonu", models.CharField(max_length=15)),
                (
                    "adres_zamieszkania",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biblioteka_app.adres",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormaKsiazki",
            fields=[
                (
                    "nazwa",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gatunek",
            fields=[
                (
                    "nazwa",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusKary",
            fields=[
                (
                    "nazwa",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusWypozyczenia",
            fields=[
                (
                    "nazwa",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Czytelnik",
            fields=[
                (
                    "uzytkownik",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="biblioteka_app.uzytkownik",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pracownik",
            fields=[
                (
                    "uzytkownik",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="biblioteka_app.uzytkownik",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ksiazka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dostepnosc", models.BooleanField()),
                (
                    "forma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.formaksiazki",
                    ),
                ),
                (
                    "gatunek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.gatunek",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pozycja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=100)),
                ("tytul", models.CharField(max_length=100)),
                (
                    "ksiazka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.ksiazka",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wypozyczenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataWypozyczenia", models.DateTimeField()),
                ("dataZwrotu", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                (
                    "pozycja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.pozycja",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.statuswypozyczenia",
                    ),
                ),
                (
                    "czytelnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.czytelnik",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rezerwacja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataRezerwacji", models.DateTimeField()),
                (
                    "ksiazka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.ksiazka",
                    ),
                ),
                (
                    "czytelnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.czytelnik",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wartosc", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.statuskary",
                    ),
                ),
                (
                    "czytelnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.czytelnik",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Katalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pracownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteka_app.pracownik",
                    ),
                ),
            ],
        ),
    ]
