# Generated by Django 5.0.1 on 2024-01-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "biblioteka_app",
            "0002_czytelnik_formaksiazki_gatunek_pracownik_statuskary_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wypozyczenie",
            name="pozycja",
        ),
        migrations.AddField(
            model_name="ksiazka",
            name="autor",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ksiazka",
            name="tytul",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wypozyczenie",
            name="ksiazka",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="biblioteka_app.ksiazka",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Pozycja",
        ),
    ]
